package:
    type:           yii2-extension
    name:           hidev-hiqdev
    title:          DEPRECATED in favour of hiqdev/hidev-hiqdev
    headline:       DEPRECATED HiDev HiQDev
    keywords:       hiqdev, hidev, vendor, config
    namespace:      hidev\hiqdev
    description:    |
        DEPRECATED in favour of [hiqdev/hidev-hiqdev](https://github.com/hiqdev/hidev-hiqdev).
        ===========================================

        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.

        This plugin provides [HiQDev](https://github.com/hiqdev) vendor configuration for HiDev.
        Used for HiQDev packages. Can be used as template for configs of other vendors.

        Provides HiQDev information and settings:

        - general data: vendor name and company title
        - contact data: email, forum, github page
        - authors data: names, roles, emails, github and home pages
        - default license: BSD-3-Clause

        See [src/config/goals.yml](src/config/goals.yml).

include:
    - src/config/goals.yml

